# Type your text here
def derive2e():
    print("Programe qui calcule derive en un nombre pour un plynome du 2nd degres")
    print("")
    print("")
    a = float(input("Choix de a : "))
    b = float(input("Choix de b : "))
    c = float(input("Choix de c : "))
    d = float(input("Antécédent du nb dérivé : "))
    A = str(a)
    B = str(b)
    C = str(c)
    D = str(d)
    print("")
    print("")
    print("f("+D+"+h) = "+A+"("+D+"+h)**2+"+B+"("+D+"+h)+"+C)
    print("f("+D+"+h) = "+A+"("+str(d**2)+"+"+str(2*d)+"h"+"+h**2)+"+str(b*d)+"+"+B+"h+"+C)
    print("f("+D+"+h) = "+str((d**2)*a)+"+"+str(2*d*a)+"h"+"+"+A+"h**2+"+str(b*d)+"+"+B+"h+"+C)
    print("f("+D+"+h) = "+str(((d**2*a)+(b*d)+c))+"+"+str((2*d*a)+b)+"h"+"+"+A+"h**2")
    print("")
    print("")
    print("f("+D+") = "+A+"*"+D+"**2+"+B+"*"+D+"+"+C)
    print("f("+D+") = "+str(a*(d**2))+"+"+str(b*d)+"+"+C)
    print("f("+D+") = "+str(a*(d**2)+b*d+c))
    print("")

    s = str(str(((d**2*a)+(b*d)+c))+"+"+str((2*d*a)+b)+"h"+"+"+A+"h**2")
    p = str(str(a*(d**2)+b*d+c))
    print("t = "+"("+s+"-"+p+")/h")
    print("t = ("+str((2*d*a)+b)+"h"+"+"+A+"h**2)/h")
    print("t = "+str((2*d*a)+b)+"+"+A+"h")
    print("")
    x = a*d*2+b
    print("lim t = "+str((2*d*a)+b))
    print("h→0")
    print("")
    print("f'("+D+") = "+str((2*d*a)+b))