def derive_3e_cal() :
    print("Programe qui calcule derive en un nombre pour un plynome du 3e degres")
    print("")
    print("")
    a = float(input("Choix de a : "))
    b = float(input("Choix de b : "))
    c = float(input("Choix de c : "))
    d = float(input("Choix de d : "))
    e = float(input("Antecedent du nb dérive : "))
    A = str(a)
    B = str(b)
    C = str(c)
    D = str(d)
    E = str(e)
    print("")
    print("")
    print("f("+E+"+h) = "+A+"("+E+"+h)**3+"+B+"("+E+"+h)**2+"+C+"("+E+"+h)+"+D)
    print("f("+E+"+h) = "+A+"("+str(e**3)+"+"+str(3*(e**2))+"h+"+str(3*e)+"h**2"+"+**3)+"+B+"("+str(e**2)+"+"+str(2*e)+"h"+"+h**2)+"+C+"("+E+"+h)+"+D)
    print("f("+E+"+h) = "+str(a*(e**3))+"+"+str(a*3*(e**2))+"h+"+str(a*3*e)+"h**2"+A+"h**3+"+str(e**2*b)+"+"+str(2*e*b)+"h"+B+"h**2+"+str(e*c)+"+"+C+"h+"+D)
    print("f("+E+"+h) = "+str((a*(e**3))+(e**2*b)+(e*c)+d)+"+"+str((a*3*(e**2))+(2*e*b)+c)+"h+"+str((a*3*e)+b)+"h**2+"+A+"h**3")
    print("")
    print("f("+E+") = "+A+"*"+E+"**3+"+B+"*"+E+"**2+"+C+"*"+E+"+"+D)
    print("f("+E+") = "+str(a*(e**3))+"+"+str((b*(e**2)))+"+"+str(c*e)+"+"+D)
    print("f("+E+") = "+str((a*(e**3))+(b*(e**2))+(c*e)+d))
    print("")
    print("t = ("+str((a*(e**3))+(e**2*b)+(e*c)+d)+"+"+str((a*3*(e**2))+(2*e*b)+c)+"h+"+str((a*3*e)+b)+"h**2+"+A+"h**3"+"-"+str((a*(e**3))+(b*(e**2))+(c*e)+d)+")/h")
    print("t = ("+str((a*3*(e**2))+(2*e*b)+c)+"h+"+str((a*3*e)+b)+"h**2+"+A+"h**3"+")/h")
    print("t = "+str((a*3*(e**2))+(2*e*b)+c)+"+"+str((a*3*e)+b)+"h+"+A+"h**2")
    print("")
    print("lim t = "+str((a*3*(e**2))+(2*e*b)+c))
    print("h→0")
    print("")
    print("f'("+E+") = "+str((a*3*(e**2))+(2*e*b)+c))