print("- OLD (1er) :")
print("Propriété :")
print("  a) e**0 = 1 et e**1 = e")
print("  b) e**x > 0 et (e**x)' = e**x")
print("  c) e**x+y = e**x * e**y")
print("  e**x-y = e**x / e**y")
print("  e**-x = 1 / e**x")
print("  (e**x)**n = e**nx\n")
print("Equation de la tangeante avec 0 :")
print("  y = f(0) * (x-0) + f(0)")
print("  y = 2x + 1 (exemple)")
print("  --> en y = 1 elle augmente de deux case\n")
print("Etudier les variations :")
print("  f(x) = (x+1)e**x")
print("  u = (x + 1) | u' = 1 #toujours positif je crois")
print("  v = e**x    | v' = e**x")
print("  f'(x) = u * v' + u' * v")
print("  f'(x) = e**x(x+2)")
print("  e**x est toujours positif")
print("  x = -2 donc sa commence négatif")
print("  x |-infi -2 +infi|")
print("  f'|  -   |   +   |")
print("  f |  - f(-2) +   |")
print("  f(-2) = (-2 + 1)e**-2 = -e**-2 = - 1/e**2\n")
print("- NEW (terminal) :")
print("Une exponentielle est strictement")
print("positive et croissant sur R\n")
print("Propiétés :")
print("e**0 = 1 | e**1 = e (~2,718)")
print("e**x > 0 | e**x+y = e**x * e**y")
print("e**x-y = e**x / e**y | e**-x = 1 / e**x")
print("(e**x)**n = e**(x * n)")
print("e**a = e**b ---> a = b")
