# Programme d'urgence du chapitre 2 d'ES PC

#print("                                          |")"
print("I. La structure critalline")
print("1. Le chlorure de sodium")
print("Le sel, ou chlorure de sodium, de formule")
print("NaCl, est présent sous sa forme solide dans")
print("certaines roches, ou provient de")
print("l'évaporation de l'eau de mer.")
print("Au niveau microscopique, le chlorure de")
print("sodium solide est constitué d'un empilement")
print("régulier d'ions sodium (Na+) et d'ions")
print("chlorure (Cl-) : c'est l'état cristallin.")
print("Au niveau macroscopique, les cristaux de  ")
print("chlorure de sodium ont une forme cubique")
print("similaire à l'organisation macroscopique.")
print("")
print("2. Les caractèristiques de la structure cristalline")
print("Une structure cristalline est définit par")
print("la répétition périodique dans l'espace d'une")
print("structure élémentaire appelée maille élémentaire.")
print("Un crystal se caractèrise par :")
print("- La forme géométrique de la maille")
print("- La nature des entitées qui le constitue,")
print("généralement un atome, une molécule ou des ions")
print("- La position des entitées chimique dans la maille")
