print("Degrès en radiant :")
print("Degrès  | 0 |  30  |  45  |  60  |  90  | 180 | 360 |")
print("Radiant | 0 | π/6  | π/4  | π/3  | π/2  |  π  | 2π  |")
print("")
print("Cosinus et Sinus :")
print("   x   | 0 | π/6  | π/4  | π/3  | π/2 |  π  |")
print(" cos x | 1 | √3/2 | √2/2 | 1/2  |  0  | -1  |")
print(" sin x | 0 | 1/2  | √2/2 | √3/2 |  1  |  0  |")
print("")
print("Formules :")
print("1. cos(-x) = cos x       | sin(-x) = -sin x")
print("2. cos(π + x) = -cos x   | sin(π + x) = -sin x")
print("3. cos(π - x) = -cos x   | sin(π - x) = sin x")
print("4. cos(π/2 + x) = -sin x | sin(π/2 + x) = cos x")
print("5. cos(π/2 - x) = sin x  | sin(π/2 - x) = cos x")