print("Degrès en radiant :")
print("Degrès  | 0 |  30  |  45  |  60  |  90  | 180 | 360 |")
print("Radiant | 0 | Pi/6 | Pi/4 | Pi/3 | Pi/2 | Pi  | 2Pi |")
print("")
print("Cosinus et Sinus :")
print("   x   | 0 | Pi/6 | Pi/4 | Pi/3 | Pi/2 | Pi  |")
print(" cos x | 1 | √3/2 | √2/2 | 1/2  |  0   | -1  |")
print(" sin x | 0 | 1/2  | √2/2 | √3/2 |  1   |  0  |")
print("")
print("Formules :")
print("1. cos(-x) = cos x        | sin(-x) = -sin x")
print("2. cos(Pi + x) = -cos x   | sin(Pi + x) = -sin x")
print("3. cos(Pi - x) = -cos x   | sin(Pi - x) = sin x")
print("4. cos(Pi/2 + x) = -sin x | sin(Pi/2 + x) = cos x")
print("5. cos(Pi/2 - x) = sin x  | sin(Pi/2 - x) = cos x")